### ISSUE TITLE
Error in -removepops

### ISSUE THREAD

**Issue by OmidJa** [laninsky/GBS_SNP_filter#1]
Hi,
This is Omid and I am working on GBS data for a fish species and the vcf file is generated from stacks pipeline. I am using your package for filtering and I think it works well until the time of LD filtering. I should add that I have the .ld files per each pop but for the final file in .vcf format I have nothing. Here is the error which I faced and I will be so grateful if you can help me to solve this error.
```
Error in -removepops : invalid argument to unary operator 
Execution halted
```
Regards,
Omid

**Comment by laninsky** [comment]
Hi Omid,

Thanks for raising this issue! I wrote this filter for a dataset where we had quite a few "bad" samples for one of the populations, and the line that didn't work for you was assuming that you'd have populations that needed to be removed from the dataset because all of the individuals within that population had been removed. I think I've fixed the issue - could you re-download GBS_SNP_filter_rsq.R and try again? If it works then I'll close off the issue. 

Let me know what other bugs you find! Hard to control for accidentally making code specific to one dataset!

Cheers,

Alana

**Comment by OmidJa** [comment]
Hi dear Alana,
Thanks for your kind answer and help. Actually I did based on your comment and downloaded the updated GBS_SNP_filter_rsq.R , and now in the step like yesterday I have a new bug which is different from the previous one.
```
Error in matrix(if (is.null(value)) logical() else value, nrow = nr, dimnames = list(rn,  :
  length of 'dimnames' [2] not equal to array extent
Calls: Ops.data.frame -> matrix
```
Can you please let me know how we can cope with it?
Thank you very much in advance.

Regards,
Omid

**Comment by laninsky** [comment]
Hi Omid,

Well at least we solved the first problem :)

This second one is a little trickier for me to track down without playing around with the data myself. Would it be possible to get a copy of your original vcf, popmap.txt, and GBS_SNP_filter.txt files you've been using emailed to [me](alana.alexander@otago.ac.nz)?

If this isn't an option for privacy reasons etc let me know - the 'slower' way will be for me to add some checks to the code so we can figure out exactly where it is failing and why.

Thanks for your patience!

Alana

**Comment by OmidJa** [comment]
Hello dear Alana,Thank you very much for your support.Here I have attached popmap.txt and GBS_SNP_filter.txt files but for the .vcf file I will send it to you right away after this email using Dropbox because of it's size.
Look forward to hearing from you.
Thank you very much in advance,
Regards,Omid

    On Sunday, March 3, 2019, 10:08:46 PM GMT+1, Alana Alexander <notifications@github.com> wrote:  
 
 
Hi Omid,

Well at least we solved the first problem :)

This second one is a little trickier for me to track down without playing around with the data myself. Would it be possible to get a copy of your original vcf, popmap.txt, and GBS_SNP_filter.txt files you've been using emailed to me?

If this isn't an option for privacy reasons etc let me know - the 'slower' way will be for me to add some checks to the code so we can figure out exactly where it is failing and why.

Thanks for your patience!

Alana

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
   
batch_1.vcf
0.65
0.9
0.01
0.5
3
GFO-1	A
GFO-2	A
GFO-3	A
GFO-4	A
GFO-5	A
GFO-6	A
GFO-7	A
GFO-8	A
GFO-9	A
GFO-10	A
GFO-11	A
GFO-12	A
GFO-14	A
GFO-15	A
GFO-18	A
GFO-19	A
GFO-20	A
GFO-21	A
GFO-22	A
GFO-23	TA
GFO-24	TA
GFO-25	TA
GFO-26	TA
GFO-27	TA
GFO-28	TA
GFO-29	TA
GFO-30	TA
GFO-31	TA
GFO-32	TA
GFO-33	TA
GFO-34	TA
GFO-35	TA
GFO-36	TA
GFO-37	TA
GFO-38	TA
GFO-39	TA
GFO-40	TA
GFO-41	TA
GFO-42	TA
GFO-43	TA
GFO-44	TA
GFO-45	TA
GFO-47	TA
GFO-48	TA
GFO-49	TA
GFO-50	TA
GFO-51	TA
GFO-52	TA
GFO-53	TA
GFO-55	TA
GFO-56	TA
GFO-58	TA
GFO-59	TA
GFO-60	TA
GFO-61	TA
GFO-62	M
GFO-69	M
GFO-72	M
GFO-73	M
GFO-74	M
GFO-75	M
GFO-76	M
GFO-77	M
GFO-78	M
GFO-79	M
GFO-80	M
GFO-81	M
GFO-82	M
GFO-83	M
GFO-84	M
GFO-87	M
GFO-88	G
GFO-90	G
GFO-91	G
GFO-92	G
GFO-93	G
GFO-96	G
GFO-98	G
GFO-99	G
GFO-100	G
GFO-101	G
GFO-102	G
GFO-103	G
GFO-104	G
GFO-105	G
GFO-119	G
GFO-120	P
GFO-121	P
GFO-122	P
GFO-123	P
GFO-124	P
GFO-125	P
GFO-126	P
GFO-127	P
GFO-128	P
GFO-129	P
GFO-130	P
GFO-131	P
GFO-132	P
GFO-133	P
GFO-134	P
GFO-135	G
GFO-136	G
GFO-137	G
GFO-138	G
GFO-139	G
GFO-140	G
GFO-141	G
GFO-142	G
GFO-143	G
GFO-144	G
GFO-145	G
GFO-146	G
GFO-147	G
GFO-148	G
GFO-149	G
GFO-150	G

**Comment by laninsky** [comment]
Awesome, thanks Omid. I've got the invitation to the dropbox link, but it is currently empty - are you in the process of uploading the vcf? GBS_SNP_filter.txt and popmap.txt look absolutely fine, so I'm curious to try and figure out why the code has suddenly stopped working! :)

**Comment by laninsky** [comment]
Cool, came through on that link, thanks! I'll be back in touch (hopefully in the next day or so) once I figure out what has gone wrong.

**Comment by OmidJa** [comment]
Hello again dear Alana,Right now I have sent my files to you.
Regards,Omid
    On Monday, March 4, 2019, 5:51:31 AM GMT+1, Alana Alexander <notifications@github.com> wrote:  
 
 
Awesome, thanks Omid. I've got the invitation to the dropbox link, but it is currently empty - are you in the process of uploading the vcf? GBS_SNP_filter.txt and popmap.txt look absolutely fine, so I'm curious to try and figure out why the code has suddenly stopped working! :)

**Comment by laninsky** [comment]
Hi Omid,

Thanks for your file - I'm currently running it through to figure out why it failed at that step, but in the mean time I think I've found another potential issue. The dataset that I wrote this code for was assembled _de novo_ so the locus identifier was contained in the #CHROM column of the vcf. However, based on the GenBank codes under #CHROM in your file, you must have used a reference-guided assembly approach right? The code as it is written is taking just one SNP per scaffold, which I bet is not what you want. You probably want it to allow for multiple SNPs per scaffold, and instead use the ID column to identify the RAD/GBS locus and take just one SNP per those loci? This shouldn't be too hard to fix, but will require the code to be rewritten a smidgen, which will take me a couple of days. I just want to confirm that is how you'd want to use this code before I go too far down the rabbit hole!

Cheers,

Alana

**Comment by OmidJa** [comment]
Hi dear Alana,Well, yes, I used the reference based pipeline of stacks to take the vcf file. Yes I definitely want it for multiple SNPs per scaffold and again take one SNP per locus, because it is more probable that SNPs in the same locus are going to be linked.Just a question, what is your suggestion to me? better to keep one SNP per locus? Because it is a genetic population study and I will be grateful if you can give me your advise.
Regards,Omid   

 On Monday, March 4, 2019, 6:27:53 AM GMT+1, Alana Alexander <notifications@github.com> wrote:  
 
 
Hi Omid,

Thanks for your file - I'm currently running it through to figure out why it failed at that step, but in the mean time I think I've found another potential issue. The dataset that I wrote this code for was assembled de novo so the locus identifier was contained in the #CHROM column of the vcf. However, based on the GenBank codes under #CHROM in your file, you must have used a reference-guided assembly approach right? The code as it is written is taking just one SNP per scaffold, which I bet is not what you want. You probably want it to allow for multiple SNPs per scaffold, and instead use the ID column to identify the RAD/GBS locus and take just one SNP per those loci? This shouldn't be too hard to fix, but will require the code to be rewritten a smidgen, which will take me a couple of days. I just want to confirm that is how you'd want to use this code before I go too far down the rabbit hole!

Cheers,

Alana

**Comment by laninsky** [comment]
Hi Omid,

Cool - I'll go ahead and get those changes going then. I think you probably want to ditch everything but one SNP/locus because over the short 100-200bp length of GBS/RADseq loci, those sites are unlikely to be regularly broken up by recombination. If you use STRUCTURE or similar programs that assume that loci are unlinked then you definitely want to ditch SNPs that are likely to be linked. So yes, your plan sounds like a good one. I'll post here again once I have a new version of the code for you to try out.

Cheers,

Alana

**Comment by laninsky** [comment]
Hi Omid,

I've made a new branch of the repo that can allow you to specify what you want to consider the "SNP locus" (in your case, the ID column, not the #CHROM column). The big differences with the previous version are that you will have to add an extra two lines to GBS_filter_SNP.txt giving the column in the vcf file that contains the locus names (in your case, ID), and the regex to strip away anything that isn't the locus name (in your case, the ID column contains the locus name combined with the position within that locus that the SNP occurred at e.g. 223111_6 is locus 223111 with a SNP at position 6. The regex to get rid of the trailing _ and number would be _.*

This branch is at the following link if you want to run it yourself (but I've also uploaded the files to the dropbox link you shared with me):
https://github.com/laninsky/GBS_SNP_filter/tree/reference_assembled_options

To demonstrate how to specify the column and regex pattern in the README I've included a very small snippet of your vcf file. Please let me know if this is not OK and I can put some dummy data up instead.

Once I hear back from you I will pull these changes in to the main version of the repo.

Cheers,

Alana

**Comment by OmidJa** [comment]
Hello dear Alana,
Hope you are fine. I should be really grateful for this your great help and support and also the very clear explanations to me. I checked it and it works well on the vcf file that I sent to you. 
It is no problem at all and I get happy if it can be as an example for better understanding the process.
Again I really appreciate all your kind supports and will back to you again if I find any bug.

Best regards,
Omid

**Comment by laninsky** [comment]
Awesome, thanks for all the help providing your dataset to solve this issue, Omid! I've gone ahead and merged the two branches, so the updated code is now available at the master branch (https://github.com/laninsky/GBS_SNP_filter). Cheers!

**Comment by OmidJa** [comment]
Hello dear Alana,
I am the one who should be rally grateful for all your supports to solve the bug. I have downloaded it.
Wish you the best,
Cheers,Omid
    On Wednesday, March 6, 2019, 11:52:18 PM GMT+1, Alana Alexander <notifications@github.com> wrote:  
 
 
Awesome, thanks for all the help providing your dataset to solve this issue, Omid! I've gone ahead and merged the two branches, so the updated code is now available at the master branch (https://github.com/laninsky/GBS_SNP_filter). Cheers!
