### ISSUE TITLE
ld performance in the package

### ISSUE THREAD

**Issue by OmidJa** [laninsky/GBS_SNP_filter#11]
Dear Alana,
Hope you are fine.
Actually I just have a question about the ld option in your GBS_SNP_filter package. If two loci are in ld, then both of them will be removed or one of them will be retained?

Thank you for all your supports.

Regards,
Omid

**Comment by laninsky** [comment]
Hi Omid,

In the [detailed workflow](https://github.com/laninsky/GBS_SNP_filter#detailed-workflow) we mention that the LD step is used to "chuck out one out of a pair of loci in LD across P populations" (i.e. one of them is retained). Do you think this wording is clear enough? Happy to update it if you think putting it another way would help.

Cheers,

Alana

**Comment by OmidJa** [comment]
Hi Alana,
Sorry I didn't pay attention to that sentence. It is completely clear to be understood.

Thank you very much.

Cheers,
Omid
