### ISSUE TITLE
locus ID regex pattern when column has colons

### ISSUE THREAD

**Issue by quinn-ca** [laninsky/GBS_SNP_filter#13]
I'm putting togther the GBS_SNP_filter.txt file and am a bit confused about line 8: the locus ID regex pattern. I have a reference-aligned vcf file output from Stacks v2. The #CHROM column is the scaffold the locus was assembled against, followed by POS and ID columns. The locus ID is in the 'ID' column but also has additional information, separated by colons. For example: (columns #CHROM, POS, ID) - ENA|CAJHIB020000001|CAJHIB020000001.1   13970   3:73:+.

From the ReadMe, it looks like I need to use a regex pattern because of the formatting of the locus ID column. I'm a bit confused about what that would look like in my case and if the colons in the ID column will be a problem, given what's mentioned in the ReadMe ("the locus name should not have a colon in it, because everything following the colon will be stripped away following the LD step").

I would appreciate any guidance on this!

**Comment by laninsky** [comment]
Hi Quinn,

Really having to rack my memory here, but I think unfortunately the ":" limitation comes through with the use of PLINK by the package downstream (it is the one that can't handle colons in the name). Could you post a couple of lines of the #CHROM POS ID columns here? That might help us plan a solution!

Cheers,

Alana

**Comment by quinn-ca** [comment]
Hi Alana,

Thanks for your help! Attached is the first few lines of my vcf file (only the first 3 columns). I've thinned my vcf file with plink previously and haven't had problems. I'm primarily interested in the HWE filtering and using this script to filter out loci that are out of HWE in each of the 4 populations (per Pearman et al. (2022) - Commonly used Hardy–Weinberg equilibrium filtering schemes impact population structure inferences using RADseq data). 

Thanks!

[chrm_loci_populations.snps.txt](https://github.com/laninsky/GBS_SNP_filter/files/10956553/chrm_loci_populations.snps.txt)

**Comment by laninsky** [comment]
Hi Quin,

Cool - to me it looks like your ID column is going to be unique even if everything following the first ':' is stripped away (based on this wee sample size). If you are worried that that might not be the case (i.e. you might have multiple sites that start with the same number), an option would be to run some kind of regex find and replace, and substitute something like an underscore for the colon. Can you test out and see whether the scripts work OK for you? (hopefully no other bugs pop up!). If it does, I will tweak the README to say you **can** have colons, but anything before the colon needs to be unique.

**Comment by quinn-ca** [comment]
Great, thanks! I filtered to have a single snp per locus, so they should all be unique (that may not be the case for those who kept multiple snps per locus). The script worked, although I added `:.*` to the 8th line because I kept getting an error saying my GBS_SNP_filter.txt file didn't have 8 lines. Thank you for your help!

**Comment by laninsky** [comment]
Thanks Quinn - sorry about this slow response - I'll close the issue and add that workaround to the readme.
