### ISSUE TITLE
Error using HWE.R

### ISSUE THREAD

**Issue by carlahurt** [laninsky/GBS_SNP_filter#14]
Hello,
  I have come across an error at the HWE step.  The error message reads, 
"Error in names(hwetablebin) <- c("snp", popnames) :
  'names' attribute [9] must be the same length as the vector [1]
Execution halted
ls: cannot access *pop.vcf: No such file or directory"

I do get the HWE table in the outfiles, but the HWE.vcf does not get written.  
I would appreciate any suggestions.

**Comment by laninsky** [comment]
Hi Carla - is the example dataset working for you? After confirming that it is (i.e. your installation is all good), I think I'll need to your input files to try and pinpoint where the error is creeping in.

**Comment by carlahurt** [comment]
Thank you for your quick response! I ran the example file successfully, so it must be something with my input files.  I'm attaching my logfile, VCF, GBS_SNP_Filter.txt, and popmap.txt file here. 
I appreciate any suggestions you might have.

[popmap.txt](https://github.com/laninsky/GBS_SNP_filter/files/11584726/popmap.txt)
[GBS_SNP_filter.txt](https://github.com/laninsky/GBS_SNP_filter/files/11584727/GBS_SNP_filter.txt)
[BTM.vcf.txt](https://github.com/laninsky/GBS_SNP_filter/files/11584728/BTM.vcf.txt)
[slurm-1542889.out.txt](https://github.com/laninsky/GBS_SNP_filter/files/11584729/slurm-1542889.out.txt)

**Comment by laninsky** [comment]
Hi Carla - heaps of apologies on the length of time on this, but I've been away from the office - back on it and trying to sleuth out what is going on. Please feel free to pester if you haven't heard back from me in a week!

**Comment by carlahurt** [comment]
Hi Alana,

  Thank you for getting back to me. While I couldn't figure out what happened with that dataset,  I reran ipyrad and my new VCF files runs perfectly on GBS_SNP filter.  This program is a lifesaver. Thank you so much for making it available.!



Carla Hurt
Associate Professor of Biology
Tennessee Tech University
(931) 372-3143
https://sites.tntech.edu/hurtlab
________________________________

**Comment by laninsky** [comment]
Ha! OK, given that magically solved the issue I'll close this issue for now, but if it crops up again let me know, and I'll resume the sleuthing.
