### ISSUE TITLE
unknown issue

### ISSUE THREAD

**Issue by ldutoit** [laninsky/GBS_SNP_filter#3]
Hi laninsky,

thank you very much for your sweet package!

I am running into an issue

```
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: readr
Loading required package: stringr
Loading required package: tibble
Parsed with column specification:
cols(
  .default = col_character(),
  `1864` = col_double(),
  `15` = col_double()
)
See spec(...) for full column specifications.
Error in stri_count_regex(string, pattern, opts_regex = opts(pattern)) :
  object 'ALT' not found
Calls: %>% ... mutate.tbl_df -> mutate_impl -> str_count -> stri_count_regex
In addition: Warning message:
Duplicated column names deduplicated: '.' => '._1' [6], '0/0:25:25,0:40:-0.00,-9.18,-124.38' => '0/0:25:25,0:40:-0.00,-9.18,-124.38_1' [17], '0/0:18:18,0:40:-0.00,-7.07,-90.18' => '0/0:18:18,0:40:-0.00,-7.07,-90.18_1' [24], '0/0:23:23,0:40:-0.00,-8.57,-114.61' => '0/0:23:23,0:40:-0.00,-8.57,-114.61_1' [26], '0/0:40:40,0:40:-0.00,-13.69,-197.66' => '0/0:40:40,0:40:-0.00,-13.69,-197.66_1' [30], '0/0:28:28,0:40:-0.00,-10.08,-139.03' => '0/0:28:28,0:40:-0.00,-10.08,-139.03_1' [31], '0/0:30:30,0:40:-0.00,-10.68,-148.81' => '0/0:30:30,0:40:-0.00,-10.68,-148.81_1' [32], '0/0:15:15,0:40:-0.00,-6.17,-75.53' => '0/0:15:15,0:40:-0.00,-6.17,-75.53_1' [34], '0/0:35:35,0:40:-0.00,-12.19,-173.23' => '0/0:35:35,0:40:-0.00,-12.19,-173.23_1' [36], '0/0:23:23,0:40:-0.00,-8.57,-114.61' => '0/0:23:23,0:40:-0.00,-8.57,-114.61_2' [37], '0/0:14:14,0:40:-0.00,-5.86,-70.64' => '0/0:14:14,0:40:-0.00,-5.86,-70.64_1' [39], '0/0:18:18,0:40:-0.00,-7.07,-90.18' => '0/0:18:18,0:40:-0.00,-7.07,-90.18_2' [43], '0/0:19:1 [... truncated]
Execution halted
ls: cannot access *pop.vcf: No such file or directory
Loading required package: dplyr

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: readr
Loading required package: stringr
Loading required package: tibble
Parsed with column specification:
cols(
  X1 = col_character()
)
```
grateful for any help!

My parameters file:

```
cat GBS_SNP_filter.txt


test.vcf
0.0
1
0.05
0.5
1
```

file attached ( test.vcf but called test.vcf.txt for upload authorisations
[test.vcf.txt](https://github.com/laninsky/GBS_SNP_filter/files/3061328/test.vcf.txt)
)!

**Comment by laninsky** [comment]
Hiya Ludo,

Thanks for lodging this issue - can I grab your popmap.txt file off you too? https://github.com/laninsky/GBS_SNP_filter#popmaptxt

Ta!

Alana

**Comment by ldutoit** [comment]
yes of course!

[popmap.txt](https://github.com/laninsky/GBS_SNP_filter/files/3061695/popmap.txt)

**Comment by laninsky** [comment]
Thanks Ludo - you've indeed found a bug in how the code handles "./." when the coverage of 0 is not explicitly given. I will do my best to fix this tomorrow and let you know :)

**Comment by ldutoit** [comment]
no worries at all, nor emergency!

I hope it helps your code.

Cheers

Ludo

**Comment by laninsky** [comment]
Kia ora Ludo - think I've fixed this (and a few other 'knock on' issues the fix caused :P ), and the new code now seems to be working on your dataset. However, your GBS_SNP_filter.txt file would also need to be tweaked a little to something along the lines of the following (rather than the seven line file you sent me originally):
```
test.vcf
0.0
1
0.05
0.5
1
#CHROM

```
I've added in a check to make sure that folks have enough stuff in GBS_SNP_filter.txt so hopefully this will fail at the beginning rather than half-way through in the future :) Let me know if the readme needs some more work on describing how to set up the GBS_SNP_filter.txt file, otherwise if it now seems to be working on your 'proper' dataset, let me know and I'll close this issue.

**Comment by ldutoit** [comment]
great thanks, super awesome sweet stuff!

Ludo
