### ISSUE TITLE
Error in generating the .ld.vcf file (the final step)

### ISSUE THREAD

**Issue by OmidJa** [laninsky/GBS_SNP_filter#8]
Dear Alana,
Hope you are fine.
Again this is Omid and sorry because of a new error. Actually I am working on the same samples as previous but today I decided to generate a vcf file including two populations and when I decided to use your package for filtering I faced with the following error. I will be so grateful if you can help to overcome this error.

```
Parsed with column specification:
cols(
  CHR_A = col_character(),
  BP_A = col_double(),
  SNP_A = col_character(),
  CHR_B = col_character(),
  BP_B = col_double(),
  SNP_B = col_character(),
  R2 = col_double(),
  X8 = col_logical()
)
Parsed with column specification:
cols(
  CHR_A = col_character(),
  BP_A = col_double(),
  SNP_A = col_character(),
  CHR_B = col_character(),
  BP_B = col_double(),
  SNP_B = col_character(),
  R2 = col_double(),
  X8 = col_logical()
)
Warning messages:
1: Missing column names filled in: 'X8' [8]
2: Missing column names filled in: 'X8' [8]
[1] "Up to 2 out of 13 pairwise LD comparisons"
Error in if (is.na(SNP_record[(j - 1), 8])) { :
  argument is of length zero
Execution halted
```
I also will send you my files through Dropbox.

Thank you very much in advance.

Regards,

Omid

**Comment by laninsky** [comment]
Hi Omid - thanks for sending me these files and logging this error. I'm away at a conference for the next two days, but will get to it after I get back. Sorry my pipeline keeps throwing bugs at you!

**Comment by OmidJa** [comment]
> Hi Omid - thanks for sending me these files and logging this error. I'm away at a conference for the next two days, but will get to it after I get back. Sorry my pipeline keeps throwing bugs at you!

It is highly appreciated. I really like your pipeline since it is very user friendly.

**Comment by laninsky** [comment]
HI Omid - sorry for the delay, but this bug should now be fixed! It was a bit of superfluous code present from way back in the beginning when I was writing/testing out the LD filter. It would only affect any vcf file that had less than five populations but more than two loci in LD, so took it took your dataset to reveal it. Sorry again for the inconvenience - I've run the code through and the 'final' vcf file is present in the Dropbox folder you shared with me, but if you want to run it again yourself, if you clone the current version of the directory that should work too!

**Comment by OmidJa** [comment]
> HI Omid - sorry for the delay, but this bug should now be fixed! It was a bit of superfluous code present from way back in the beginning when I was writing/testing out the LD filter. It would only affect any vcf file that had less than five populations but more than two loci in LD, so took it took your dataset to reveal it. Sorry again for the inconvenience - I've run the code through and the 'final' vcf file is present in the Dropbox folder you shared with me, but if you want to run it again yourself, if you clone the current version of the directory that should work too!

Hi dear Alana,

Thank you very much for all your great helps. Now it is working properly and I got the vcf out puts.

Yours sincerely,

Omid
